name: Docker CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_SEC }}" | docker login -u "nutan1909" --password-stdin

      - name: Build Docker Image
        run: docker build -t nutan1909/your-image-name:latest .

      - name: Push Docker Image
        run: docker push nutan1909/your-image-name:latest
