name: Docker Build and Run

on:
  push:
    branches: [main]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}       # Your Docker Hub username secret
        password: ${{ secrets.DOCKER_PASSWORD }}       # Your Docker Hub access token/password secret

    - name: Build Docker image
      run: docker build -t nutan1909/flask-form-app:latest .

    - name: Push Docker image to Docker Hub
      run: docker push nutan1909/flask-form-app:latest

    - name: Run container (test run)
      run: |
        docker run -d --name test-flask-app -p 5000:5000 nutan1909/flask-form-app:latest
        sleep 10
        docker ps | grep test-flask-app

    - name: Stop container after test
      if: always()
      run: docker stop test-flask-app && docker rm test-flask-app
