name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t flask-form-app .
    - name: Push to Docker Hub or GitHub Container Registry
      run: echo "Push step here..."
    - name: Deploy to K8s
      run: echo "Deploy to cluster using kubectl or SSH"
